app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, SubmitField, PasswordField, DecimalField, HiddenField,
                     RadioField, SelectField, BooleanField, DateField, IntegerField)
from wtforms.widgets import TextArea
from wtforms.validators import Email, DataRequired, Length, EqualTo, optional


class SignUpForm(FlaskForm):
    email = StringField('Email', validators=[Email(), DataRequired()])
    password1 = PasswordField('Password',
                              validators=[DataRequired(), Length(min=8)])
    password2 = PasswordField('Confirm password',
                              validators=[DataRequired(),
                                          EqualTo('password1',
                                                  message="Passwords do not match.")])
    submit = SubmitField('Submit')


class LogInForm(FlaskForm):
    email = StringField('Email', validators=[Email(), DataRequired()])
    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=8)])
    submit = SubmitField('Submit')


class ProfileForm(FlaskForm):
    public_email = StringField('Public Email', validators=[Email()])
    title_th = StringField('Title', validators=[Length(max=128)])
    academic_title_th = StringField('Academic Title', validators=[Length(max=128)])
    firstname_en = StringField('English First Name')
    lastname_en = StringField('English Last Name')
    firstname_th = StringField('Thai First Name')
    lastname_th = StringField('Thai Last Name')
    phone = StringField('Phone')
    street = StringField('Street', widget=TextArea())
    submit = SubmitField('Submit')

cell_availability = [
    ('0', 'Available with no restrictions'),
    ('1', 'Available for non-commercial research only'),
    ('2', 'Currently not available')
]

class RegisterCellForm(FlaskForm):
    cell_type = RadioField('Cell Type',
                           choices=[('hiPSC', 'hiPSC'), ('hESC', 'hESC'), ('MSC', 'MSC')],
                           default='hiPSC',
                           validators=[DataRequired()])
    institution = SelectField('Institution',
                              validators=[DataRequired(), ])
    comment = StringField('Comment', widget=TextArea())
    alternative_names = StringField('Alternative Name(s)')
    available = SelectField('Availability', choices=cell_availability)
    karyotyped = SelectField('Has the cell line been karyotyped?',
                             choices=[('no', 'No'), ('yes', 'Yes')],
                             default='no')
    karyotype = StringField('Karyotype')
    source_cell_type = StringField('Source cell type')
    source_cell_origin = StringField('Source cell origin')
    donor_age_collection = IntegerField('Age of donor (at collection)', validators=[optional()])
    collected_in = IntegerField('Collected in', validators=[optional()])
    passage_no = IntegerField('Passage number reprogrammed')
    vector_type = SelectField('Vector type', choices=[('Non-integrating', 'Non-integrating')],
                              validators=[optional()])
    vector = StringField('Vector')
    selection_criteria = StringField('Selection criteria for clones')
    xeno_free = SelectField('Derived under xeno-free conditions',
                            choices=[('no', 'No'), ('yes', 'Yes')],
                            default='no')
    under_gmp = SelectField('Derived under GMP?',
                            choices=[('no', 'No'), ('yes', 'Yes')],
                            default='no')
    clinical_grade_avail = SelectField('Available as clinical grade?',
                                       choices=[('no', 'No'), ('yes', 'Yes')],
                                       default='no')
    donor_gender = SelectField('Sex', choices=[('male', 'Male'), ('female', 'Female')],
                               default='male')
    donor_diseases = StringField('Diseases')
    donor_disease_assoc_phenotypes = StringField('Disease associated phenotypes')
    donor_karyotyped = SelectField('Has the donor karyotype been analyzed?',
                                   choices=[('no', 'No'), ('yes', 'Yes')],
                                   default='no')
    donor_gws = SelectField('Is there genome-wide genotyping or functional data available?',
                            choices=[('no', 'No'), ('yes', 'Yes')],
                            default='no')
    culture_surface_coating = StringField('Surface Coating')
    culture_feeder_cells = SelectField('Feeder cells',
                                       choices=[('no', 'No'), ('yes', 'Yes')],
                                       validators=[optional()])
    culture_passage_method = StringField('Passage Method')
    culture_o2_conc = DecimalField('O2 Concentration', validators=[optional()])
    culture_co2_conc = DecimalField('CO2 Concentration', validators=[optional()])
    culture_medium = StringField('Medium')
    culture_rock_inhibitor_used_at_passage = SelectField('Has Rock inhibitor (Y27632) been used at passage previously with this cell line?',
                                                         choices=[('no', 'No'), ('yes', 'Yes')],
                                                         default='no')
    culture_rock_inhibitor_used_at_cryo = SelectField('Has Rock inhibitor (Y27632) been used at cryo previously with this cell line?',
                                                      choices=[('no', 'No'), ('yes', 'Yes')],
                                                      default='no')
    culture_rock_inhibitor_used_at_thaw = SelectField('Has Rock inhibitor (Y27632) been used at thaw previously with this cell line?',
                                                      choices=[('no', 'No'), ('yes', 'Yes')],
                                                      default='no')
    character = HiddenField('Characteristics')
    diff_potency_endoderm = StringField('Endoderm')
    diff_potency_mesoderm = StringField('Mesoderm')
    diff_potency_ectoderm = StringField('Ectoderm')

    embryo_stage = StringField('Embryo Stage')
    ivf_treatment = SelectField('Supernumerary embryos from IVF treatment?',
                                choices=[('no', 'No'), ('yes', 'Yes')],
                                default='no')
    pgd_embryo = SelectField('PGD Embryo?',
                             choices=[('no', 'No'), ('yes', 'Yes')],
                             default='no')
    zp_removal_technique = StringField('ZP removal technique')
    cell_isolation = StringField('Cell isolation')
    cell_seeding = StringField('Cell seeding')


    marker_Alkaline_Phosphatase_enzyme = StringField('Enzymatic Assay')
    marker_Alkaline_Phosphatase_expr_profile = StringField('Expression Profiles')

    submit = SubmitField('Submit')


class RegisterProjectForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    acronym = StringField('acronym')
    summary = StringField('summary', widget=TextArea())
    website = StringField('website')
    startdate = DateField('Start Date', validators=[optional()])
    enddate = DateField('End Date', validators=[optional()])
    sponsor_name = StringField('Sponsor Name')
    institution = StringField('Institution Name')
    submit = SubmitField('Submit')

app/main/__init__.py
from flask import Blueprint

mainbp = Blueprint('main', __name__)

from . import views

app/main/views.py
from datetime import datetime
import pytz
from flask import render_template, redirect, request, url_for
from . import mainbp as main
from .forms import SignUpForm, LogInForm, ProfileForm, RegisterCellForm, RegisterProjectForm
from collections import defaultdict
from .models import User, Project, Event, Cell, ApprovalStatus, Institution, UserProfile
from .models import InstitutionSchema, CellSchema
from ..app import db
from flask_login import login_user, current_user, logout_user, login_required
from json import loads
from werkzeug.security import generate_password_hash


@main.route('/', methods=['GET', 'POST'])
def index():
    error_msg = defaultdict(list)
    form = SignUpForm()
    if form.validate_on_submit():
        user_ = User.query.filter_by(email=form.email.data).first()
        if user_:
            return redirect(url_for('main.log_user_in', user_exist=form.email.data))
        else:
            new_user = User(email=form.email.data,
                            password=form.password1.data)
            profile = UserProfile(public_email=form.email.data)
            new_user.profile = profile
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            return redirect(url_for('main.edit_profile'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                error_msg[field].append(error)

    projects = Project.query.all()[:3]
    events = Event.query.all()[:5]
    cells = Cell.query.all()[:5]

    return render_template('main/index.html', form=form,
                           error_msg=error_msg,
                           projects=projects,
                           events=events,
                           cells=cells,
                           )


@main.route('/login_form', methods=['GET', 'POST'])
def log_user_in():
    error_msg = ''
    if current_user.is_authenticated:
        return redirect(url_for('main.account_dash'))
    form = LogInForm()
    if request.args.get('user_exist', False):
        error_msg = 'Email account already exists. Please log in.'
        form.email.data = request.args.get('user_exist')
    if form.validate_on_submit():
        email = request.form.get('email')
        user = User.query.filter_by(email=email).first()
        if user:
            pw = request.form.get('password')
            if user.verify_password(pw):
                login_user(user, remember=True)
                return redirect(request.args.get('next', url_for('main.account_dash')))
            else:
                error_msg = 'Password is not correct.'
        else:
            error_msg = 'Email does not exist.'
    else:
        for field, errors in form.errors.items():
            for error in errors:
                error_msg += ' ' + error

    return render_template('main/login.html', form=form,
                           error_msg=error_msg)


@main.route('/logout_form', methods=['GET', 'POST'])
@login_required
def log_user_out():
    if current_user.is_authenticated:
        form = LogInForm()
        logout_user()
        return render_template('main/logout.html', form=form)
    else:
        return redirect(url_for('main.log_user_in'))


@main.route('/account/dashboard')
@login_required
def account_dash():
    projects = {'pending': 0, 'approved': 0, 'total': 0}
    cells = {'pending': 0, 'approved': 0, 'total': 0}
    affil_cells = {'pending': 0, 'approved': 0, 'total': 0}
    affil_researchers = []
    affil_projects = {'pending': 0, 'approved': 0, 'total': 0}
    if current_user.profile.affil is not None:
        for researcher in current_user.profile.affil.affiliates:
            for proj in researcher.user.created_projects:
                if proj.status.status == 'pending':
                    affil_projects['pending'] += 1
                elif proj.status.status == 'approved':
                    affil_projects['approved'] += 1
                affil_projects['total'] += 1
            affil_researchers.append(researcher)
            for cell in researcher.user.own_cells:
                if cell.status.status == 'pending':
                    affil_cells['pending'] += 1
                elif cell.status.status == 'approved':
                    affil_cells['approved'] += 1
                affil_cells['total'] += 1

    for proj in current_user.created_projects:
        if proj.status.status == 'pending':
            projects['pending'] += 1
        elif proj.status.status == 'approved':
            projects['approved'] += 1
        projects['total'] += 1

    for cell in current_user.own_cells:
        if cell.status.status == 'pending':
            cells['pending'] += 1
        elif cell.status.status == 'approved':
            cells['approved'] += 1
        cells['total'] += 1

    return render_template('main/account_dash.html',
                           projects=projects,
                           affil_cells=affil_cells,
                           affil_projects=affil_projects,
                           affil_researchers=affil_researchers,
                           cells=cells,
                           page_name='dashboard')


@main.route('/account/projects')
@login_required
def account_projects():
    status_filter = request.args.get('status_filter', None)
    projects = []
    for proj in current_user.created_projects:
        if not proj.cell:
            cell_id = None
            cell_type = None
        else:
            cell_id = proj.cell.id
            cell_type = proj.cell.cell_type
        projects.append({
            'id': proj.id,
            'title': proj.title,
            'affil': proj.institution.name_th,
            'startdate': proj.startdate,
            'enddate': proj.enddate,
            'status': proj.status.status,
            'creator': {
                'email': proj.creator.email,
                'firstname': proj.creator.profile.first_name_th,
                'lastname': proj.creator.profile.last_name_th,
                'affil': proj.creator.profile.affil.name_th,
            },
            'view_count': proj.view_count,
            'summary': proj.summary[:300],
            'cell_id': cell_id,
            'cell_type': cell_type
        })

    if status_filter is None or status_filter == 'all':
        filtered_projects = projects
        status_filter = None
    else:
        filtered_projects = [p for p in projects if p['status'] == status_filter]

    return render_template('main/account_projects.html',
                           projects=filtered_projects,
                           status_filter=status_filter,
                           page_name='project')


@main.route('/projects')
def show_projects():
    query = request.args.get('q', None)
    projects = []
    for proj in Project.query.all():
        if not proj.cell:
            cell_id = None
            cell_type = None
        else:
            cell_id = proj.cell.id
            cell_type = proj.cell.cell_type
        projects.append({
            'id': proj.id,
            'title': proj.title,
            'affil': proj.institution.name_th,
            'startdate': proj.startdate,
            'enddate': proj.enddate,
            'status': proj.status.status.title(),
            'creator': {
                'email': proj.creator.email,
                'firstname': proj.creator.profile.first_name_th,
                'lastname': proj.creator.profile.last_name_th,
                'affil': proj.creator.profile.affil.name_th,
            },
            'view_count': proj.view_count,
            'summary': proj.summary[:300],
            'cell_id': cell_id,
            'cell_type': cell_type
        })

    if query:
        filtered_projects = []
        for p in projects:
            if query.lower() in p['title'].lower() or query.lower() in p['summary'].lower():
                filtered_projects.append(p)
    else:
        filtered_projects = projects
    return render_template('main/projects.html',
                           query=query,
                           projects=filtered_projects)


@main.route('/project/<int:project_id>')
def display_project_info(project_id):
    project = Project.query.get(project_id)
    project.view_count += 1
    project.last_view = datetime.now(tz=pytz.UTC)
    db.session.add(project)
    db.session.commit()
    return render_template('main/project_detail.html', project=project)


@main.route('/account/profile/edit', methods=['POST', 'GET'])
@login_required
def edit_profile():
    msg = None
    error_msg = {}
    institutions = Institution.query.all()
    institution_schema = InstitutionSchema(many=True)
    pf = current_user.profile
    form = ProfileForm()
    if form.validate_on_submit():
        if pf.affil is None:
            institution_name_th = request.form.get('hidden_institution')
            existing_institution = Institution.query.filter_by(name_th=institution_name_th).first()
            if existing_institution:
                pf.affil = existing_institution
            else:
                new_institution = Institution(name_th=institution_name_th,
                                              campus=request.form.get('hidden_campus', ''),
                                              adder=current_user,
                                              name_en=request.form.get('hidden_name_en', ''))
                pf.affil = new_institution
                db.session.add(new_institution)
                db.session.commit()
        pf.public_email = form.public_email.data
        pf.academic_title_th = form.academic_title_th.data
        pf.title_th = form.title_th.data
        pf.first_name_en = form.firstname_en.data
        pf.last_name_en = form.lastname_en.data
        pf.first_name_th = form.firstname_th.data
        pf.last_name_th = form.lastname_th.data
        pf.phone = form.phone.data
        pf.street = form.street.data
        db.session.add(pf)
        db.session.commit()

app/templates/main/account_base.html
{% extends "base.html" %}
{% block title %}Thai SCReg Main Page{% endblock %}
{% block content %}
    <section class="hero is-info is-bold is-small">
        <div class="hero-head">
            {% include "main/navbar.html" %}
        </div>
        <div class="hero-body">
            <div class="container">
                <p><h1 class="title">{{ current_user.profile.academic_title_th or '' }} {{ current_user.profile.first_name_th or '' }} {{ current_user.profile.last_name_th or '' }}</h1>
                <h1 class="subtitle">{{ current_user.profile.first_name_en or '' }} {{ current_user.profile.last_name_en or ''}}</h1></p>
                <p><h1 class="subtitle">สังกัด {{ current_user.profile.affil.name_th or '-' }} วิทยาเขต {{ current_user.profile.affil.campus or '-'}}</h1></p>
            </div>
        </div>
        <div class="hero-foot">
            <nav class="tabs is-boxed is-fullwidth">
                <div class="container">
                    <ul>
                        <li {% if page_name=='dashboard' %}class="is-active"{% endif %}>
                            <a href="{{ url_for('main.account_dash') }}">Overview</a>
                        </li>
                        <li {% if page_name=='profile' %}class="is-active"{% endif %}>
                            <a href="{{ url_for('main.edit_profile') }}">Profile</a>
                        </li>
                        <li {% if page_name=='cell' %}class="is-active"{% endif %}>
                            <a href="{{ url_for('main.account_cells') }}">Cells</a>
                        </li>
                        <li {% if page_name=='project' %}class="is-active"{% endif %}>
                            <a href="{{ url_for('main.account_projects') }}">Project</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </section>
    <section class="section">
        {% block account_content %}
        {% endblock %}
    </section>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', () => {

            // Get all "navbar-burger" elements
            const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

            // Check if there are any navbar burgers
            if ($navbarBurgers.length > 0) {

                // Add a click event on each of them
                $navbarBurgers.forEach(el => {
                    el.addEventListener('click', () => {

                        // Get the target from the "data-target" attribute
                        const target = el.dataset.target;
                        const $target = document.getElementById(target);

                        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                        el.classList.toggle('is-active');
                        $target.classList.toggle('is-active');

                    });
                });
            }

        });
    </script>
{% endblock %}

app/templates/main/account_projects.html
{% extends "main/account_base.html" %}

{% block account_content %}
        <div class="container">
            <div class="columns">
                <div class="column has-text-right">
                    <a class="button is-link is-rounded"
                       href="{{ url_for('main.register_project') }}"
                    >
                        <span class="icon">
                            <i class="fas fa-plus"></i>
                        </span>&nbsp;
                        Register Project
                    </a>
                </div>
            </div>
            <div class="columns">
                <div class="column">
                    <div class="box" id="app">
                        {% if status_filter %}
                            <div class="tags has-addons">
                                <span class="tag">Filter</span>
                                <span class="tag {% if status_filter=='approved' %}is-success{% else %}is-warning{% endif %}">{{ status_filter }}</span>
                            </div>
                        {% endif %}
                        <b-table
                                :data="data"
                                ref="table"
                                paginated
                                per-page="5"
                                detailed
                                detail-key="id"
                        >
                            <template slot-scope="props">
                                <b-table-column field="id" label="ID" numeric>
                                    <% props.row.id %>
                                </b-table-column>
                                <b-table-column field="title_th" label="Title" width="300" sortable>
                                    <a @click="toggle(props.row)">
                                        <% props.row.title %>
                                    </a>
                                </b-table-column>
                                <b-table-column field="affil" label="Affiliation" width="300" sortable>
                                    <% props.row.affil %>
                                </b-table-column>
                                <b-table-column field="startdate" label="Start Date" sortable>
                                    <% props.row.startdate %>
                                </b-table-column>
                                <b-table-column field="enddate" label="End Date" sortable>
                                    <% props.row.enddate %>
                                </b-table-column>
                                <b-table-column field="status" label="Status" sortable>
                                    <% props.row.status %>
                                </b-table-column>
                                <b-table-column field="view" label="View">
                                    <a v-bind:href="'/project/'+props.row.id">
                                        <span class="icon">
                                            <i class="far fa-eye"></i>
                                        </span>
                                        <span class="tag"><% props.row.view_count %></span>
                                    </a>
                                </b-table-column>
                            </template>
                            <template slot="detail" slot-scope="props">
                                <article class="media">
                                    <div class="media-content">
                                        <div class="content">
                                            <p>
                                                <strong>Created by <% props.row.creator.firstname %> <% props.row.creator.lastname %></strong>
                                                <small>
                                                    <span class="icon">
                                                        <i class="fas fa-envelope"></i>
                                                    </span>&nbsp;<% props.row.creator.email %>
                                                    &nbsp;
                                                    <span class="icon">
                                                        <i class="fas fa-landmark"></i>
                                                    </span>&nbsp;<% props.row.creator.affil %>
                                                </small>
                                                <br>
                                                <div class="field is-grouped is-grouped-multiline">
                                                    <div class="control">
                                                        <a v-bind:href="'/cell/'+props.row.cell_id">
                                                            <div class="tags has-addons">
                                                                <span class="tag is-dark"><% props.row.cell_type %></span>
                                                                <span class="tag is-info">
                                                                <strong>THSCR-<% props.row.cell_id %></strong>
                                                            </span>
                                                            </div>
                                                        </a>
                                                    </div>
                                                </div>
                                                <br>
                                                <small><% props.row.summary %></small>
                                                <a v-bind:href="'/project/'+props.row.id"
                                                   class="button is-light is-small is-rounded">
                                                    See detail
                                                </a>
                                            </p>
                                        </div>
                                    </div>
                                </article>
                            </template>
                        </b-table>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>
        var vueApp = new Vue({
            el: '#app',
            delimiters: ['<%', '%>'],
            data() {
                return {
                    data: {{ projects|tojson|safe }}
                }
            },
            methods: {
                toggle(row) {
                    this.$refs.table.toggleDetails(row)
                },
            }
        });
    </script>
{% endblock %}

app/templates/main/navbar.html
<nav class="navbar">
    <div class="container">
        <div class="navbar-brand">
            <a href="/">
                <img src="{{ url_for('static', filename='img/logo-no-text.png') }}" width="150">
            </a>
            <a role="button" class="navbar-burger burger" aria-label="menu"
               aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>
        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-end">
                <a class="navbar-item" href="/">
                    Home
                </a>
                <a class="navbar-item" href="{{ url_for('main.show_cell_list') }}">
                    Cells
                </a>
                <a class="navbar-item" href="{{ url_for('main.show_projects') }}">
                    Projects
                </a>
                <a class="navbar-item" href="{{ url_for('main.about') }}">
                    About
                </a>
                {% if current_user.is_authenticated %}
                    <div class="navbar-item" >
                        <div class="buttons">
                            <a class="button is-rounded is-light"
                               href="{{ url_for('main.account_dash') }}">
                                            <span class="icon">
                                                <i class="fas fa-user-circle"></i>
                                            </span>&nbsp;
                                Account
                            </a>
                            <a class="button is-light is-rounded"
                               href="{{ url_for('main.log_user_out') }}">
                                            <span class="icon">
                                               <i class="fas fa-power-off"></i>
                                            </span>
                            </a>
                        </div>
                    </div>
                {% else %}
                    <div class="navbar-item">
                        <a class="button is-link is-rounded"
                           href="{{ url_for('main.log_user_in') }}">
                            Log In
                        </a>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</nav>